spring:
  profiles.active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/winestore
  jpa:
    show-sql: true
    generate-ddl: false
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  main:
    allow-circular-references: true
jwt:
  secret: "_]/G.*wg;s2_'u>7M*T96"

